using System;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEditor.UIElements;
using UnityEngine;
using UnityEngine.UIElements;

namespace RPGFramework.Battle.Editor
{
    [Serializable]
    public class BattleArenaDatabaseAssetAuthoring
    {
        public GameObject Prefab;
    }

    [CreateAssetMenu(fileName = "Battle Arena Database", menuName = "RPG Framework/Battle/Battle Arena Database")]
    public class BattleArenaDatabaseScriptableObject : ScriptableObject
    {
        private readonly string m_AssetBundlesPath = Path.Combine(Application.streamingAssetsPath, "Battle");

        public BattleArenaDatabaseAssetAuthoring[] m_Arenas;

        public void BuildScriptFile(string path, string filename, string namespaceForScript)
        {
            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }

            string filePath = Path.Combine(path, filename);

            if (File.Exists(filePath))
            {
                File.Delete(filePath);
            }

            StringBuilder sb             = new StringBuilder();
            string        scriptFileName = filename.Split('.')[0];

            sb.AppendLine("// THIS FILE IS AUTOGENERATED, DO NOT MODIFY");
            sb.AppendLine($"// Last generated at {DateTime.UtcNow}\n");

            sb.AppendLine("using RPGFramework.Battle;");
            sb.AppendLine("using System.IO;");
            sb.AppendLine("using RPGFramework.Battle.Databases;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceForScript}");
            sb.AppendLine("{");

            sb.AppendLine($"\tinternal class {scriptFileName.Replace(" ", "")} : IBattleArenaDatabase");
            sb.AppendLine("\t{");
            sb.AppendLine("\t\tprivate readonly BattleArenaDefinition[] m_Arenas;");
            sb.AppendLine();
            sb.AppendLine($"\t\tinternal {scriptFileName.Replace(" ", "")}()");
            sb.AppendLine("\t\t{");

            sb.AppendLine("\t\t\tstring assetBundlesPath = Path.Combine(Application.streamingAssetsPath, \"Battle\");");
            sb.AppendLine("\t\t\tm_Arenas = new BattleArenaDefinition[]");
            sb.AppendLine("\t\t\t{");
            for (int i = 0; i < m_Arenas.Length; i++)
            {
                sb.AppendLine($"\t\t\t\tnew BattleArenaDefinition(\"{m_Arenas[i].Prefab.name}\", Path.Combine(assetBundlesPath, \"{m_Arenas[i].Prefab.name.ToLower()}\")),");
            }

            sb.AppendLine("\t\t\t};");

            sb.AppendLine("\t\t}");

            sb.AppendLine();

            sb.AppendLine("\t\tBattleArenaDefinition IBattleArenaDatabase.Get(int index)");
            sb.AppendLine("\t\t{");
            sb.AppendLine("\t\t\treturn m_Arenas[index];");
            sb.AppendLine("\t\t}");

            sb.AppendLine("\t}");

            sb.AppendLine("}");

            string file = sb.ToString();

            File.WriteAllText(filePath, file);

            AssetDatabase.Refresh();
        }

        public void BuildAssetBundles()
        {
            if (m_Arenas.Length == 0)
            {
                return;
            }

            if (Directory.Exists(m_AssetBundlesPath))
            {
                Directory.Delete(m_AssetBundlesPath, true);
            }

            Directory.CreateDirectory(m_AssetBundlesPath);

            AssetBundleBuild[] arenasToBuild = new AssetBundleBuild[m_Arenas.Length];

            for (int i = 0; i < m_Arenas.Length; i++)
            {
                string prefabPath = AssetDatabase.GetAssetPath(m_Arenas[i].Prefab);

                arenasToBuild[i] = new AssetBundleBuild
                                   {
                                       assetBundleName = m_Arenas[i].Prefab.name,
                                       assetNames      = new string[] { prefabPath }
                                   };
            }

            BuildPipeline.BuildAssetBundles(m_AssetBundlesPath, arenasToBuild, BuildAssetBundleOptions.StrictMode, EditorUserBuildSettings.activeBuildTarget);

            AssetDatabase.Refresh();
        }
    }

    [CustomEditor(typeof(BattleArenaDatabaseScriptableObject))]
    public class BattleArenaDatabaseScriptableObjectEditor : UnityEditor.Editor
    {
        private ModalWindow m_Window;

        public override VisualElement CreateInspectorGUI()
        {
            VisualElement root = new VisualElement();

            InspectorElement.FillDefaultInspector(root, serializedObject, this);

            Button generateBattleArenaDatabaseScriptButton = new Button(OnGenerateBattleArenaDatabaseScriptButtonClicked)
                                                             {
                                                                 text = "Generate BattleArenaDatabase script"
                                                             };

            root.Add(generateBattleArenaDatabaseScriptButton);

            Button generateAssetBundlesButton = new Button(OnGenerateAssetBundlesButtonClicked)
                                                {
                                                    text = "Generate Asset Bundles"
                                                };

            root.Add(generateAssetBundlesButton);

            return root;
        }

        private void OnGenerateBattleArenaDatabaseScriptButtonClicked()
        {
            m_Window           =  CreateInstance<ModalWindow>();
            m_Window.OnConfirm += OnGenerateBattleArenaDatabaseScriptButtonClickedCallback;

            m_Window.Init(nameof(BattleArenaDatabaseScriptableObject), "Generate Asset Bundles and BattleArenaDatabase script", "BattleArenaDatabase.cs");
        }

        private void OnGenerateBattleArenaDatabaseScriptButtonClickedCallback(string path, string filename, string namespaceForScript)
        {
            m_Window.OnConfirm -= OnGenerateBattleArenaDatabaseScriptButtonClickedCallback;
            m_Window           =  null;

            BattleArenaDatabaseScriptableObject battleArenaDatabase = (BattleArenaDatabaseScriptableObject)serializedObject.targetObject;

            battleArenaDatabase.BuildScriptFile(path, filename, namespaceForScript);
        }

        private void OnGenerateAssetBundlesButtonClicked()
        {
            BattleArenaDatabaseScriptableObject battleArenaDatabase = (BattleArenaDatabaseScriptableObject)serializedObject.targetObject;

            battleArenaDatabase.BuildAssetBundles();
        }
    }

    public class ModalWindow : EditorWindow
    {
        public event Action<string, string, string> OnConfirm;

        private TextField m_PathTextField;
        private TextField m_FileNameTextField;
        private TextField m_NamespaceTextField;

        private string m_SelectedDirectory;
        private string m_AssetType;
        private string m_FileName;

        public void Init(string assetType, string windowTitle, string filename)
        {
            m_AssetType         = assetType;
            m_FileName          = filename;
            titleContent        = new GUIContent(windowTitle);
            minSize             = new Vector2(600, 200);
            m_SelectedDirectory = EditorPrefs.GetString($"{Application.productName}_SelectedDirectory_{m_AssetType}", Application.dataPath);
            ShowModal();
        }

        public void CreateGUI()
        {
            VisualElement root = rootVisualElement;

            root.style.paddingTop    = 10;
            root.style.paddingBottom = 10;
            root.style.paddingLeft   = 10;
            root.style.paddingRight  = 10;
            root.style.flexDirection = FlexDirection.Column;

            VisualElement pathRow = new VisualElement
                                    {
                                        style =
                                        {
                                            flexDirection = FlexDirection.Row,
                                            alignItems    = Align.FlexEnd
                                        }
                                    };

            m_PathTextField = new TextField("Path:")
                              {
                                  value = m_SelectedDirectory
                              };
            m_PathTextField.style.flexGrow = 1;

            Button browseButton = new Button(OnBrowseClicked)
                                  {
                                      text = "Browse"
                                  };
            browseButton.style.flexShrink = 0;

            pathRow.Add(m_PathTextField);
            pathRow.Add(browseButton);

            if (m_FileName != null)
            {
                m_FileNameTextField = new TextField("File Name:")
                                      {
                                          value = EditorPrefs.GetString($"{Application.productName}_FileName_{m_AssetType}", m_FileName)
                                      };
            }

            m_NamespaceTextField = new TextField("Namespace:")
                                   {
                                       value = EditorPrefs.GetString($"{Application.productName}_Namespace_{m_AssetType}", "MyNamespace")
                                   };

            VisualElement buttonRow = new VisualElement
                                      {
                                          style =
                                          {
                                              flexDirection  = FlexDirection.Row,
                                              justifyContent = Justify.SpaceBetween
                                          }
                                      };

            Button continueButton = new Button(OnButtonConfirm)
                                    {
                                        text = "Generate"
                                    };

            buttonRow.Add(continueButton);

            root.Add(pathRow);
            if (m_FileName != null)
            {
                root.Add(m_FileNameTextField);
            }

            root.Add(m_NamespaceTextField);
            root.Add(buttonRow);
        }

        private void OnBrowseClicked()
        {
            string folderPath = EditorUtility.OpenFolderPanel("Select Folder", m_SelectedDirectory, string.Empty);

            if (!string.IsNullOrEmpty(folderPath))
            {
                m_SelectedDirectory   = folderPath;
                m_PathTextField.value = m_SelectedDirectory;
            }
        }

        private void OnButtonConfirm()
        {
            EditorPrefs.SetString($"{Application.productName}_SelectedDirectory_{m_AssetType}", m_SelectedDirectory);
            if (m_FileName != null)
            {
                EditorPrefs.SetString($"{Application.productName}_FileName_{m_AssetType}", m_FileNameTextField.value);
            }

            EditorPrefs.SetString($"{Application.productName}_Namespace_{m_AssetType}", m_NamespaceTextField.value);

            OnConfirm?.Invoke(m_SelectedDirectory, m_FileNameTextField?.value, m_NamespaceTextField.value);
            Close();
        }
    }
}